language:
  - cpp
  - python
python:
  - "2.7"
compiler:
  - gcc
env:
  global:
    - secure: "Gi079QeYa0G/PtXrboD8tpn/GNL+VuvGisacywCIz9H9Rw4sDUXsUCOVTND43NuFRvliNcRs2zAWqmS2gzXMdRuZ8YC/MsGUyMzJ5OmxcqvfsVR4PZ65N/vlD7IPpz+BXHil73+V+8xKBRZeLtmBIEVGW2XbG/thJ2F/DYuC74s="
  matrix:
    - ROS_DISTRO=hydro  ROSWS=wstool BUILDER=catkin    USE_DEB=true
    - ROS_DISTRO=hydro  ROSWS=wstool BUILDER=catkin    USE_DEB=false      NOT_TEST_INSTALL=true
    - ROS_DISTRO=hydro  ROSWS=wstool BUILDER=catkin    USE_DEB=source
    - ROS_DISTRO=indigo  ROSWS=wstool BUILDER=catkin   USE_DEB=true
    - ROS_DISTRO=indigo  ROSWS=wstool BUILDER=catkin   USE_DEB=false      NOT_TEST_INSTALL=true
    - ROS_DISTRO=indigo  ROSWS=wstool BUILDER=catkin   USE_DEB=source
#matrix:
#   allow_failures:
#     - env: ROS_DISTRO=hydro  ROSWS=wstool BUILDER=catkin    USE_DEB=false
#     - env: ROS_DISTRO=indigo  ROSWS=wstool BUILDER=catkin   USE_DEB=true
#     - env: ROS_DISTRO=indigo  ROSWS=wstool BUILDER=catkin   USE_DEB=false
script:
  - .travis/travis.sh
after_success:
  - TRAVIS_JOB_SUBNUMBER="${TRAVIS_JOB_NUMBER##*.}"
  - if [ "$TRAVIS_JOB_SUBNUMBER" == 1 -a "$TRAVIS_BRANCH" == "gen_eusdoc" ]; then .travis/upload-docs.sh; fi
after_failure:
  - source /home/travis/ros/ws_jsk_roseus/devel/setup.bash
  - rostest -t roseus test-genmsg.catkin.test
  - rostest -t roseus test-genmsg-oneworkspace.catkin.launch
notifications:
  email:
    on_success: always
    on_failure: always
